#define FUNC 1
#define VAR 2
#define LET 3
#define IF 4
#define ELSE 5
#define WHILE 6
#define PRINT 7
#define READ 8
#define SEMICOLON 9
#define COMA 10
#define PLUS 11
#define MINUS 12
#define ASTERISC 13
#define SLASH 14
#define EQUAL 15
#define LEFTPAREN 16
#define RIGHTPAREN 17
#define LCURLYBRACKET 18
#define RCURLYBRACKET 19
#define ID 20
#define STRING 21
#define NUM 22
#define DO 23
#define AND 24
#define OR 25
#define DIFFERENT 26
#define GREATERTHAN 27
#define LESSERTHAN 28
#define GTOREQ 29
#define LSSROREQ 30
#define IGIG 31
#define FOR 32
